<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_main-search__button</name>
   <tag></tag>
   <elementGuidId>3fd351ab-6f46-4a78-9309-43c021e26d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-search > div.main-search__container > form.main-search__form > div.main-search__input-container > button.main-search__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a51d1a2-746d-4fcd-a7c6-1fe459ef9827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-search__button</value>
      <webElementGuid>9306c731-1456-4fb0-9cef-deb9ca7e14d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>05d96da6-5994-4361-ad63-bf528dce302b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>17f4f9c1-5f9e-4435-ab9d-1a959be97c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--15857958813779__main&quot;)/div[1]/div[@class=&quot;page-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main-search&quot;]/div[@class=&quot;main-search__container&quot;]/form[@class=&quot;main-search__form&quot;]/div[@class=&quot;main-search__input-container&quot;]/button[@class=&quot;main-search__button&quot;]</value>
      <webElementGuid>f7764f0c-cf8f-4951-af43-cdb2de846559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>7907bba0-ae18-4e31-a9d8-6d0acd15b006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-template--15857958813779__main']/div/div/div/div/div/form/div/button</value>
      <webElementGuid>d48db8a1-a9c5-43f1-88fd-12f70f0ce086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/following::button[1]</value>
      <webElementGuid>5b891eec-2bfc-4146-b26c-a98e19522ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[3]/following::button[1]</value>
      <webElementGuid>38c0be02-1ac2-4b18-ac7e-b8dd72920db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions:'])[1]/preceding::button[1]</value>
      <webElementGuid>1442f69b-4ee6-4aea-8a3c-0e9610f12bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adidas'])[1]/preceding::button[1]</value>
      <webElementGuid>79c46b3a-f267-4baf-9ceb-48d88281ddf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/div/button</value>
      <webElementGuid>be47e25c-6e58-48b0-8feb-a3a9f10d3bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>e03b8bd2-bf69-4171-8522-6de55756ffb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
