<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Amazon.co.jp_field-keywords</name>
   <tag></tag>
   <elementGuidId>672717d0-f102-4265-82ed-5a1b106d8e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#twotabsearchtextbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='twotabsearchtextbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search Amazon.co.jp&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66e712a6-64e5-4b2c-8900-90c50ed51015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddd15b72-d822-46b0-9d54-383868c0f36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>twotabsearchtextbox</value>
      <webElementGuid>d48c9bd0-fd0a-4a55-a181-52470e54c786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field-keywords</value>
      <webElementGuid>e2b1cb85-ee6d-4f21-a408-0dae9840cc72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>584dd545-012f-4298-a1fa-4f1a0f471e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Amazon.co.jp</value>
      <webElementGuid>370d3c96-0a4d-46ce-b791-25c0fbfc6ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-input nav-progressive-attribute</value>
      <webElementGuid>2b104e87-7eaf-4d16-8f0d-e88d24ed49f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>da096c95-c519-4580-9747-9d408ab39506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>407237cd-1067-419b-91c7-e1f75b2bcd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Amazon.co.jp</value>
      <webElementGuid>e1636792-4e95-4b6e-ad64-b6871147cd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34455ddb-ad7e-47db-a8b8-e6a9cb6f1f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;twotabsearchtextbox&quot;)</value>
      <webElementGuid>4d1490a4-dad0-4e7b-a04d-d99fffc5be9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='twotabsearchtextbox']</value>
      <webElementGuid>4904e329-588e-4d04-9273-e3a9db292703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='nav-search-bar-form']/div[2]/div/input</value>
      <webElementGuid>3a89fd7e-a5d2-4614-939a-3a6bcfcef226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ce60a102-ee4b-4d9b-ab47-fb309ce2c8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'twotabsearchtextbox' and @name = 'field-keywords' and @placeholder = 'Search Amazon.co.jp']</value>
      <webElementGuid>650c9dc0-60f8-48d7-8f6d-07f1501c4639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
