<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Moncler</name>
   <tag></tag>
   <elementGuidId>c34bcbd0-eee0-4c80-838a-a77cf78616f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.vendor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='shopify-section-template--16094672453820__collection']/div/div[2]/article/a/div[2]/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Moncler Barant Vest Rp 24.328.500&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>1a4e7def-b218-4fcb-a4c1-d5a56de1c2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vendor</value>
      <webElementGuid>67a2f6ea-3228-4907-ae21-3bb656ccd3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Moncler</value>
      <webElementGuid>b97ad7d1-c402-4c76-891e-440fd131695f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--16094672453820__collection&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;products boost-pfs-filter-products&quot;]/article[@class=&quot;product&quot;]/a[1]/div[@class=&quot;details&quot;]/h5[@class=&quot;vendor&quot;]</value>
      <webElementGuid>dc8b20db-5cf4-45db-9a8a-b082781696b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='shopify-section-template--16094672453820__collection']/div/div[2]/article/a/div[2]/h5</value>
      <webElementGuid>ce0c1ea2-ed02-4c7c-b98e-3f3a9cb104d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sale'])[1]/following::h5[1]</value>
      <webElementGuid>73852f00-0409-4a03-bc5d-9113ca626258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load Previous Page'])[1]/following::h5[1]</value>
      <webElementGuid>c4971c73-b7b4-41e8-b312-6ec74521c3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barant Vest'])[1]/preceding::h5[1]</value>
      <webElementGuid>6d639d11-4a0c-4e71-b067-e8e0a0b0bd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 24.328.500'])[1]/preceding::h5[1]</value>
      <webElementGuid>a9e89df4-c32f-48f1-bc96-97d0a8f5be98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Moncler']/parent::*</value>
      <webElementGuid>3eb05900-158e-4b65-9840-63de55e0f0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>60d544ef-5a46-4216-8b4d-79c294da0032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Moncler' or . = 'Moncler')]</value>
      <webElementGuid>b83ab126-6d7a-4d15-826d-e87432ef1d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
