<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Amazon</name>
   <tag></tag>
   <elementGuidId>3da507da-2408-4516-a887-22c02a0cb4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Bubble-module__bubble_HMAsFLoooPgV9bEqZsLu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;filter-bubble-deals-collection-amazon-devices&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>562a92d5-b47a-46ca-bb65-f25e56f2b822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>uxElement</value>
      <webElementGuid>5d64263e-aa79-435b-b0cd-e17efddffe3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-element-id</name>
      <type>Main</type>
      <value>filter-bubble-deals-collection-amazon-devices</value>
      <webElementGuid>9e387fd4-2163-4237-99b1-545bfe16b256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-element-type</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d9f08c19-da1d-4da3-9f63-97b815d17670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-painter</name>
      <type>Main</type>
      <value>discount-asin-grid</value>
      <webElementGuid>15b844f0-20e4-4b4d-9f23-e723d763d96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>filter-bubble-deals-collection-amazon-devices</value>
      <webElementGuid>a92be594-1fc8-45a7-b703-a8696bed44de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96e81e38-0f82-4412-aa72-8f4df43aa939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Bubble-module__bubble_HMAsFLoooPgV9bEqZsLu</value>
      <webElementGuid>7aa74788-82fd-4b6f-947e-c2177ab73abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>6zjgr7-4gposu-8o4sob-45ppfp</value>
      <webElementGuid>31cc72b5-1fe3-4faa-92a0-715f07dedd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amazonデバイス</value>
      <webElementGuid>a0f9191e-3cf8-45e2-9fcd-b736b6cfad7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anonCarousel7&quot;)/ol[@class=&quot;a-carousel&quot;]/li[@class=&quot;a-carousel-card&quot;]/button[@class=&quot;Bubble-module__bubble_HMAsFLoooPgV9bEqZsLu&quot;]</value>
      <webElementGuid>90261d66-48b5-4198-ac84-1e044f0c1538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='anonCarousel7']/ol/li/button</value>
      <webElementGuid>a25553c9-7d80-42d2-9e96-6b818c8da3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::button[1]</value>
      <webElementGuid>b12bf803-0e1f-4825-b48d-34aa173df3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next page'])[6]/following::button[1]</value>
      <webElementGuid>7efd896d-181c-4c9b-9734-abe724476df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='パソコン・周辺機器'])[1]/preceding::button[1]</value>
      <webElementGuid>42490b3d-5663-41a1-bb8f-d777b15598bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ファッション'])[1]/preceding::button[2]</value>
      <webElementGuid>76be4e5a-1eac-4fd6-a2b0-94fd3d695d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amazonデバイス']/parent::*</value>
      <webElementGuid>c9d81f42-eed2-4cf4-9244-2425eaad738d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2f408a79-8ea3-4c21-bc99-3b7eab468e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Amazonデバイス' or . = 'Amazonデバイス')]</value>
      <webElementGuid>895a5b62-a5b0-460d-9452-583e5a16c05a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
