<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accessibility_globalnav-menubutton-link-search</name>
   <tag></tag>
   <elementGuidId>83a8959c-a4dc-45fc-937b-7509f28a3e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#globalnav-menubutton-link-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='globalnav-menubutton-link-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search apple.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5ec620a-2cd7-4574-ae0f-6c262f5f568b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b3eb9ca-9cbf-46e0-bf4e-773cc5c6bbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>globalnav-menubutton-link-search</value>
      <webElementGuid>44016d1c-3f7f-4fa9-b1a7-0b62fee49d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/us/search</value>
      <webElementGuid>1724aaf9-a292-40f5-bc9f-857a1a259f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-topnav-flyout-trigger-regular</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>05ed9a20-5498-4d1e-aeb1-fde5c83d000d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-topnav-flyout-trigger-compact</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0887c2f2-548e-47c2-b817-ff14a8962cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search apple.com</value>
      <webElementGuid>f1a92383-844f-48cf-b9bf-fac47c162b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-title</name>
      <type>Main</type>
      <value>open - search field</value>
      <webElementGuid>60cdc3da-1495-4a52-a6f3-f1c98d932b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>globalnav-link globalnav-link-search</value>
      <webElementGuid>4313e331-d83a-4785-aa9e-524e46ac5ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus-method</name>
      <type>Main</type>
      <value>mouse</value>
      <webElementGuid>8c422e63-8643-44f7-8939-a39be0d75a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalnav-menubutton-link-search&quot;)</value>
      <webElementGuid>d97d3ab7-96be-4c03-96df-234d9f31b63b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='globalnav-menubutton-link-search']</value>
      <webElementGuid>34f321c0-c0ba-4f57-a5d8-e78caa433ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='globalnav-list']/li[3]/a</value>
      <webElementGuid>9c3ba74e-6cc4-4c19-b01c-0b9dd3c501e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/following::a[1]</value>
      <webElementGuid>58e1c1fc-5eff-4bca-9cf3-beb797e7f4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find My'])[1]/following::a[2]</value>
      <webElementGuid>a675d193-de4b-4407-9b6e-028fbca7e1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Links'])[2]/preceding::a[1]</value>
      <webElementGuid>5e7f345d-df31-470a-9537-e6ae582b4102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Store'])[2]/preceding::a[1]</value>
      <webElementGuid>21c5e816-5fe9-45ec-a59b-8499221101b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/us/search')]</value>
      <webElementGuid>c529c94f-0a0a-422b-b712-d7f7b3fe5087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>2c0b4bc1-fc99-4b31-b0cb-dc8ec8a51f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'globalnav-menubutton-link-search' and @href = '/us/search']</value>
      <webElementGuid>c0131969-f36d-4515-bcd2-c2857d69411a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
