<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accessibility_globalnav-searchfield-input</name>
   <tag></tag>
   <elementGuidId>6b919a00-6c72-45da-a24a-1fa8ff9403f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.globalnav-searchfield-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='globalnav-submenu-search']/div/div/form/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search apple.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6de7781-06dc-49a0-94b8-ed50552ac93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search apple.com</value>
      <webElementGuid>66c07a69-97a1-4fef-949a-3a18501aeb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search apple.com</value>
      <webElementGuid>571f3116-2fa2-489f-8f1b-195d8f8d74e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4099c947-ed61-466b-80c5-77576afdbe27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>875a9699-36b1-4ae3-abc0-71d9afd95d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fbb9267b-bca3-47c2-9a80-e3d36d48a9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>globalnav-searchfield-input</value>
      <webElementGuid>6a2f115b-6eea-425e-8dc9-e321e104c4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus-method</name>
      <type>Main</type>
      <value>mouse</value>
      <webElementGuid>33743e33-e92a-43cc-b2f5-08049e4dc6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalnav-submenu-search&quot;)/div[@class=&quot;globalnav-flyout-scroll-container&quot;]/div[@class=&quot;globalnav-flyout-content globalnav-submenu-content&quot;]/form[@class=&quot;globalnav-searchfield&quot;]/div[@class=&quot;globalnav-searchfield-wrapper&quot;]/input[@class=&quot;globalnav-searchfield-input&quot;]</value>
      <webElementGuid>036d1a76-5236-4d9d-b9a8-931d35cdcb8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalnav-submenu-search']/div/div/form/div/input</value>
      <webElementGuid>a00c2db8-ac2c-4990-8f78-ec768496cff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8d0af040-1cee-4c49-a385-70e990845cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search apple.com']</value>
      <webElementGuid>d617d768-b245-4470-8a11-f0800e10d866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
