<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_main-search__button</name>
   <tag></tag>
   <elementGuidId>40c22b41-d781-4061-b796-54147815b2f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-search > div.main-search__container > form.main-search__form > div.main-search__input-container > button.main-search__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1ef56e0-2151-4992-bd3a-5398d990dbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-search__button</value>
      <webElementGuid>7113c588-4d76-48dc-8989-0ebf2e44398c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5e8192f7-06ef-44f9-b9b0-96a5421d8874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>8109eb89-a798-4850-a94f-a223dede55bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--15857958813779__main&quot;)/div[1]/div[@class=&quot;page-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main-search&quot;]/div[@class=&quot;main-search__container&quot;]/form[@class=&quot;main-search__form&quot;]/div[@class=&quot;main-search__input-container&quot;]/button[@class=&quot;main-search__button&quot;]</value>
      <webElementGuid>2edb6609-bb8d-45d7-b11f-25dc58d391e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>06ddd3af-1a60-4e93-9b11-9a4aef9a666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-template--15857958813779__main']/div/div/div/div/div/form/div/button</value>
      <webElementGuid>70b1a05b-a3ef-44c2-96c8-a026415d359f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/following::button[1]</value>
      <webElementGuid>507248be-e23f-4213-830d-d534458aeb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[3]/following::button[1]</value>
      <webElementGuid>9a2ee1c8-5dbe-4af9-bc8a-030327862a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions:'])[1]/preceding::button[1]</value>
      <webElementGuid>e1a9dde8-e475-4c7a-975c-3d80773c22e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='stussy'])[1]/preceding::button[1]</value>
      <webElementGuid>b1aa421b-90c7-443e-9fc5-2cfa7e8f480d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/div/button</value>
      <webElementGuid>d7b63257-f4f7-45fd-a1ef-e5b8a2a189c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>b96263b1-f430-4f49-9e9f-9101ecebe476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
