<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_We found 214 results</name>
   <tag></tag>
   <elementGuidId>3c0375af-0d80-48d7-8db6-d6f39643f6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.utility-bar__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-template--15857958813779__main']/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;We found 214 results&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47f6b0e4-cd22-419f-840f-a44b17e65fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>utility-bar__item</value>
      <webElementGuid>abff13fb-7e4e-4444-ac2f-20181ce2c2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We found 214 results</value>
      <webElementGuid>bd020d59-d672-496b-8980-ebc1d11dafbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--15857958813779__main&quot;)/div[1]/div[@class=&quot;container container--no-max&quot;]/div[@class=&quot;utility-bar&quot;]/div[@class=&quot;utility-bar__centre&quot;]/div[@class=&quot;utility-bar__item&quot;]</value>
      <webElementGuid>efe218af-4236-406b-8948-3dd4d8366ed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-template--15857958813779__main']/div/div[2]/div/div[2]/div</value>
      <webElementGuid>7c9a280f-7632-48f7-a572-51d09e9432fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::div[2]</value>
      <webElementGuid>b9bb9dba-2a0f-4359-a3c9-087fb1b718fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/following::div[8]</value>
      <webElementGuid>6a7e53cf-0e07-48df-a915-31c9550b87a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/preceding::div[1]</value>
      <webElementGuid>a34c869f-7004-487a-b063-d8f606f3b60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[1]/preceding::div[2]</value>
      <webElementGuid>6062466b-c236-4e2a-8e37-c12af3a68b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We found 214 results']/parent::*</value>
      <webElementGuid>0f0d5ce7-0fd3-48d2-aaed-ca2abe975d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>eeffdf3c-89da-44a0-a182-654b6bf78bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'We found 214 results' or . = 'We found 214 results')]</value>
      <webElementGuid>812dd698-353c-4b86-8cd6-3462e21697f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
