<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Indonesia_a-button-input</name>
   <tag></tag>
   <elementGuidId>b0733624-b370-4ca0-96c4-0ec4dc81c848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e4016b5-1c97-4ab3-88f9-c90eda424622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-params</name>
      <type>Main</type>
      <value>{&quot;toasterType&quot;:&quot;AIS_INGRESS&quot;}</value>
      <webElementGuid>a6e2b1c3-a895-4988-91f4-4f39dde49b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-type</name>
      <type>Main</type>
      <value>DISMISS</value>
      <webElementGuid>f2393112-ac0d-4261-84f9-5a8b1e95f2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>60bc18b9-d708-41ec-8be8-8f59f24e376e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5cd80418-becf-4879-8df1-c5b34f4e7255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-main&quot;)/div[@class=&quot;nav-left&quot;]/div[@class=&quot;a-section glow-toaster glow-toaster-theme-default glow-toaster-slot-default nav-coreFlyout nav-flyout&quot;]/div[@class=&quot;glow-toaster-content&quot;]/div[@class=&quot;glow-toaster-footer&quot;]/span[@class=&quot;a-button a-spacing-top-base a-button-base glow-toaster-button glow-toaster-button-dismiss a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>167c4358-159a-40f9-aa0e-9f83f04450bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[2]</value>
      <webElementGuid>271667d3-47c5-4339-a7b0-59bcaac17781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-main']/div/div/div/div[3]/span/span/input</value>
      <webElementGuid>63aa85b2-a8df-4f78-bb25-609d70719753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>0ded30c2-8a87-4761-ab53-5ab595ecb8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>cebc7f76-ad34-4439-ae04-8d8e5101c184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
