<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clocks</name>
   <tag></tag>
   <elementGuidId>b89bede7-3bda-4b75-b380-61ae0c957d01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Clocks')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Clocks&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b5c8a57b-4080-4875-a412-cb682a0fed87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/-/en/gp/bestsellers/amazon-devices/8500435051/ref=zg_bs_nav_amazon-devices_2_2408708051</value>
      <webElementGuid>6abdbe0f-4950-423d-9252-040a76c9f575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clocks</value>
      <webElementGuid>c4395a4c-2a42-4347-a743-797aaa694f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstance6-iN9Yar62mOXvI0ONV_Rw&quot;)/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-group__88fbz&quot;]/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-group__88fbz&quot;]/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-group__88fbz&quot;]/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-item__1rdKf _p13n-zg-nav-tree-all_style_zg-browse-height-large__1z5B8&quot;]/a[1]</value>
      <webElementGuid>df342cf9-beed-488a-b038-80e8df949efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstance6-iN9Yar62mOXvI0ONV_Rw']/div[2]/div[2]/div[2]/div[5]/a</value>
      <webElementGuid>d2dcedff-5e62-4289-8647-976a8df3c4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Clocks')]</value>
      <webElementGuid>1af5998e-c1e0-4349-b1ff-02d6c0bb1a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bundles'])[1]/following::a[1]</value>
      <webElementGuid>943ee44d-4a75-4d95-bc99-cc79b6bbe1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bases &amp; Stands'])[1]/following::a[2]</value>
      <webElementGuid>91e72e70-735c-4490-b605-1d4f4da82e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Covers'])[1]/preceding::a[1]</value>
      <webElementGuid>894456ab-9bbe-4e66-97df-2f209a1f4eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboards'])[1]/preceding::a[2]</value>
      <webElementGuid>ae161297-7e04-4ad0-8bbb-7e5954781075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clocks']/parent::*</value>
      <webElementGuid>2d13db3a-a17e-4103-85b0-b5523ebc9b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/-/en/gp/bestsellers/amazon-devices/8500435051/ref=zg_bs_nav_amazon-devices_2_2408708051')]</value>
      <webElementGuid>b605cdfb-d6d3-48ef-8d67-c60f53927cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>1294f2f5-9242-4817-9fa7-f907277fa921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/-/en/gp/bestsellers/amazon-devices/8500435051/ref=zg_bs_nav_amazon-devices_2_2408708051' and (text() = 'Clocks' or . = 'Clocks')]</value>
      <webElementGuid>09ff3409-9f87-4762-a2dc-95ec564ff7cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
