<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__a-dynamic-image p13n-sc-dynamic-image _885a43</name>
   <tag></tag>
   <elementGuidId>c5309479-5c89-40cd-b97f-12322198d797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='桃太郎電鉄ワールド ～地球は希望でまわってる！～|オンラインコード版']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;桃太郎電鉄ワールド ～地球は希望でまわってる！～|オンラインコード版&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0014d55c-9be8-46b0-9b01-d7eb116b46fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>桃太郎電鉄ワールド ～地球は希望でまわってる！～|オンラインコード版</value>
      <webElementGuid>27078507-c8b0-4b80-bc7f-2ec4023de865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-fe.ssl-images-amazon.com/images/I/91A2OiJu+ML._AC_UL330_SR330,330_.jpg</value>
      <webElementGuid>e5b7c601-7318-4c4d-bc3c-af59b0cf77b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dynamic-image p13n-sc-dynamic-image p13n-product-image</value>
      <webElementGuid>73c31b75-f506-4fef-9fdf-9fbe3f048889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>165px</value>
      <webElementGuid>10689a8c-fe6c-4368-b776-543f20cce5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-dynamic-image</name>
      <type>Main</type>
      <value>{&quot;https://images-fe.ssl-images-amazon.com/images/I/91A2OiJu+ML._AC_UL165_SR165,165_.jpg&quot;:[165,165],&quot;https://images-fe.ssl-images-amazon.com/images/I/91A2OiJu+ML._AC_UL330_SR330,330_.jpg&quot;:[330,330],&quot;https://images-fe.ssl-images-amazon.com/images/I/91A2OiJu+ML._AC_UL495_SR495,495_.jpg&quot;:[495,495]}</value>
      <webElementGuid>e70effd1-1eae-4238-8b71-95180afb79ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anonCarousel26&quot;)/ol[@class=&quot;a-carousel&quot;]/li[@class=&quot;a-carousel-card&quot;]/span[1]/div[@class=&quot;p13n-sc-uncoverable-faceout&quot;]/a[@class=&quot;a-link-normal aok-block&quot;]/div[@class=&quot;a-section a-spacing-mini _cDEzb_noop_3Xbw5&quot;]/img[@class=&quot;a-dynamic-image p13n-sc-dynamic-image p13n-product-image&quot;]</value>
      <webElementGuid>09c65c19-af1b-4fed-a748-f52bbb3a10f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='anonCarousel26']/ol/li[2]/span/div/a/div/img</value>
      <webElementGuid>3596dcf4-59a4-4119-8539-978fa82e8e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='桃太郎電鉄ワールド ～地球は希望でまわってる！～|オンラインコード版']</value>
      <webElementGuid>095883fb-f13f-4561-a3bb-d927bc8680f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span/div/a/div/img</value>
      <webElementGuid>8ce08666-3889-498b-8f33-a70e40111676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '桃太郎電鉄ワールド ～地球は希望でまわってる！～|オンラインコード版' and @src = 'https://images-fe.ssl-images-amazon.com/images/I/91A2OiJu+ML._AC_UL330_SR330,330_.jpg']</value>
      <webElementGuid>96361f79-36e0-48cb-836e-5e7faac638da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
