<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Amazon.co.jp_field-keywords</name>
   <tag></tag>
   <elementGuidId>8da6552f-c5d4-4cec-805d-7a8e856414b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#twotabsearchtextbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='twotabsearchtextbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search Amazon.co.jp&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0993c318-1181-4b12-baaf-887ff7963184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa8e26a0-16bc-4f19-b254-66f94c3e8c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>twotabsearchtextbox</value>
      <webElementGuid>95a1c354-e6d0-41e4-9659-b0114ec2ec06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field-keywords</value>
      <webElementGuid>bda956bb-0303-4be3-95e8-19e443165e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d77772d0-63d3-4c34-9088-55eab0c2ed34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Amazon.co.jp</value>
      <webElementGuid>92ceeac0-a6ff-4c4c-a1e8-065621ac9b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-input nav-progressive-attribute</value>
      <webElementGuid>f2b08491-d39d-4bf3-af7f-565feee76ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b63f9a86-a601-429a-af69-c09188afb152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>85b2dd28-ab48-4866-a1db-aa52854d1bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Amazon.co.jp</value>
      <webElementGuid>4d8ed693-5614-433c-a3f9-fbfe04cf497e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0fe95754-7486-4d0d-8b70-6f44c9f64752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;twotabsearchtextbox&quot;)</value>
      <webElementGuid>faabee1f-a5a0-45f4-b827-6e729afb4def</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='twotabsearchtextbox']</value>
      <webElementGuid>4d6d8937-df8c-40d5-95d1-5d66435b8094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='nav-search-bar-form']/div[2]/div/input</value>
      <webElementGuid>e64b26d0-29ba-4da1-9b38-120a0d962e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>16f27ddd-3759-4c4b-83aa-2d8e19a3282d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'twotabsearchtextbox' and @name = 'field-keywords' and @placeholder = 'Search Amazon.co.jp']</value>
      <webElementGuid>cd9bdcb2-36ce-4564-a694-da3bae9ad32f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
