<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DATA_DRIVEN_AIRBNB_EXP_WITH_CSV</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>45dcbc9e-da44-465a-8ab6-21a9da30291e</testSuiteGuid>
   <testCaseLink>
      <guid>1cfd755f-ed2c-4683-a1ad-39ee356fb760</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AIRBNB_EXPERIENCE/EXPERIENCE_CITY_01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>36a3ebcb-f072-449f-bf0e-1f5e8776551b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AIRBNB_DATA_DRIVEN/EXP_AIR_BNB_CSV</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>36a3ebcb-f072-449f-bf0e-1f5e8776551b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Tujuan</value>
         <variableId>b3f9f087-a879-4967-a002-9cc109f8be88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>36a3ebcb-f072-449f-bf0e-1f5e8776551b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Jumlah</value>
         <variableId>f1029a3c-29f0-48e9-8f9a-d740dfd15356</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
