<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DATA_DRIVEN_EXT_03</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5ad91b58-1163-4fab-8db9-49965be3d053</testSuiteGuid>
   <testCaseLink>
      <guid>5844bdab-7c3c-4020-ba93-8434e8ee1ccc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AIRBNB_EXPERIENCE/EXPERIENCE_CITY_02</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>65025180-3e46-4444-b9c2-d0a4669ef581</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AIRBNB_DATA_DRIVEN/EXP_AIR_BNB_CSV</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>65025180-3e46-4444-b9c2-d0a4669ef581</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Tujuan</value>
         <variableId>5200856b-f70b-48dc-b707-43eb6a090629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>65025180-3e46-4444-b9c2-d0a4669ef581</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Jumlah</value>
         <variableId>8dd4d4dd-2b8c-4e5c-9e7b-950a3d080fd5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
