<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Audio</name>
   <tag></tag>
   <elementGuidId>a1e45631-d32c-4afb-a3a9-33c2bf3cac90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Audio')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Audio&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>532f274a-c1b8-4141-8b19-34397608908e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/-/en/gp/bestsellers/amazon-devices/2408708051/ref=zg_bs_nav_amazon-devices_2_2408696051</value>
      <webElementGuid>3363c4d2-44cd-4d6e-970f-04f0556e8075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Audio</value>
      <webElementGuid>db5f1cb3-d868-401b-8ee2-a74b7e90e187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceuNrBSj0G6W2BHHbotY-9Hw&quot;)/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-group__88fbz&quot;]/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-group__88fbz&quot;]/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-group__88fbz&quot;]/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-item__1rdKf _p13n-zg-nav-tree-all_style_zg-browse-height-large__1z5B8&quot;]/a[1]</value>
      <webElementGuid>2635c3fd-82a8-42b3-bfc5-706112eb2ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceuNrBSj0G6W2BHHbotY-9Hw']/div[2]/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>7c562604-6bf9-41cf-8839-ecbecd9b2345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Audio')]</value>
      <webElementGuid>da42d592-620d-4202-891f-b81a88f8bacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adapters &amp; Connectors'])[1]/following::a[1]</value>
      <webElementGuid>acece65f-ad2c-4cbb-8a65-74e30d396a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Device Accessories'])[1]/following::a[2]</value>
      <webElementGuid>93b6fd52-b853-4c81-9e77-ad32a1a12e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bases &amp; Stands'])[1]/preceding::a[1]</value>
      <webElementGuid>520ed60e-eae5-40a0-9b0c-4db269f653c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bundles'])[1]/preceding::a[2]</value>
      <webElementGuid>da8215ae-4bf8-4c07-8187-4ce01d0e6636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Audio']/parent::*</value>
      <webElementGuid>3733b438-e3a0-463d-bd24-7af93466f6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/-/en/gp/bestsellers/amazon-devices/2408708051/ref=zg_bs_nav_amazon-devices_2_2408696051')]</value>
      <webElementGuid>ba6ca818-83e4-42b9-afc3-d5d063cef824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>ea80d88b-f91f-40a7-9e82-c56ba16e986f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/-/en/gp/bestsellers/amazon-devices/2408708051/ref=zg_bs_nav_amazon-devices_2_2408696051' and (text() = 'Audio' or . = 'Audio')]</value>
      <webElementGuid>948f1b9f-6c02-4f72-bea6-7710c1e549a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
