<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_31</name>
   <tag></tag>
   <elementGuidId>c283d166-ec18-4a4b-be19-876f82c765c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._vpnq80j.notranslate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-tabpanel']/div/div[3]/div/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div/div[3]/div/table/tbody/tr[5]/td[7]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;31, Saturday, August 2024&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d7331e1-0ad3-443e-b01e-fcec33f0e09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_vpnq80j notranslate</value>
      <webElementGuid>23913901-4a71-4910-ba44-4d6d3756e6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calendar-day-08/31/2024</value>
      <webElementGuid>ebae0372-e9fb-469d-a4fa-9a6a97531301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-day-blocked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eac92e75-b070-4f92-a7e2-995a78dd0dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>8d6eba68-bd8b-4556-bcf7-b279f5f38e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-tabpanel&quot;)/div[@class=&quot;ir2ixub atm_9s_1txwivl atm_h_1h6ojuz atm_am_163v1yp atm_e2_1osqo2v atm_jb_idpfg4 atm_mj_1wugsn5 dir dir-ltr&quot;]/div[@class=&quot;c111bvlt atm_am_16wc86f atm_9s_1txwivl atm_1eltean_1osqo2v dir dir-ltr&quot;]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;coy2xq9 atm_mk_stnw88 atm_tk_1osqo2v atm_wq_kb7nvz atm_26_1p8m8iw atm_5j_1vi7ecw atm_70_z3lat3 atm_gp_1fwxnve atm_iy_1xor2vp atm_l0_15vqwwr atm_l1_1wugsn5 atm_l2_1f51e7f atm_lb_4n2dxu atm_lh_swyrjs atm_5sxl3l_16m390d__1v156lz favrsqg atm_n3_idpfg4 l1hvhoo atm_fq_idpfg4 dir dir-ltr&quot;]/div[@class=&quot;dvp1orm atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_l8_10us9ju dir dir-ltr&quot;]/div[@class=&quot;d1hw4v9n atm_e2_1osqo2v atm_j6_1665v6k dir dir-ltr&quot;]/div[@class=&quot;_g2s11rv&quot;]/div[1]/div[1]/div[@class=&quot;_14676s3&quot;]/div[@class=&quot;_1foj6yps&quot;]/div[@class=&quot;_2hyui6e&quot;]/div[@class=&quot;_1lds9wb&quot;]/div[@class=&quot;_ytfarf&quot;]/table[@class=&quot;_cvkwaj&quot;]/tbody[1]/tr[5]/td[@class=&quot;_1uhba3zj&quot;]/div[@class=&quot;_vpnq80j notranslate&quot;]</value>
      <webElementGuid>a193e980-ee8a-4aa2-9de2-c79a4136b2d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div[3]/div/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div/div[3]/div/table/tbody/tr[5]/td[7]/div</value>
      <webElementGuid>25d73073-2a27-45c9-b6cd-4699f1aa798e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='August 2024'])[1]/following::div[33]</value>
      <webElementGuid>6317b4d6-45c4-4424-acee-574a811fddf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 2024'])[1]/following::div[69]</value>
      <webElementGuid>0dbdc450-1967-4c68-96a5-e28238c38741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='September 2024'])[1]/preceding::div[1]</value>
      <webElementGuid>74b6d5dc-00dd-49ca-95bf-705aee279a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::div[34]</value>
      <webElementGuid>106e61e1-d70f-40bf-a802-9c4fb6c2e72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[5]/td[7]/div</value>
      <webElementGuid>d160213c-e066-4192-ab2c-1a0663227ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '31' or . = '31')]</value>
      <webElementGuid>3c22a700-6d04-49b8-b252-d017cfd5ba42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
