<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_28</name>
   <tag></tag>
   <elementGuidId>4901ebe1-1f3a-4040-a15e-528ea3f603a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(5) > td._sl5yz7r > div._1xnkk5ra.notranslate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-tabpanel']/div/div[3]/div/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[5]/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;28, Sunday, July 2024&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6920317c-97f8-4ecc-955c-2f32a55df17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1xnkk5ra notranslate</value>
      <webElementGuid>08dd7f42-c54e-40bd-9375-beeb188193ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>calendar-day-07/28/2024</value>
      <webElementGuid>bb57380e-ded6-4595-84c3-59f4b0157794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-day-blocked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a46c250-f6f6-4edb-b713-66a191ffe706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>fead3ed6-ac66-40eb-ad2e-202a5366b247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-tabpanel&quot;)/div[@class=&quot;ir2ixub atm_9s_1txwivl atm_h_1h6ojuz atm_am_163v1yp atm_e2_1osqo2v atm_jb_idpfg4 atm_mj_1wugsn5 dir dir-ltr&quot;]/div[@class=&quot;c111bvlt atm_am_16wc86f atm_9s_1txwivl atm_1eltean_1osqo2v dir dir-ltr&quot;]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;coy2xq9 atm_mk_stnw88 atm_tk_1osqo2v atm_wq_kb7nvz atm_26_1p8m8iw atm_5j_1vi7ecw atm_70_z3lat3 atm_gp_1fwxnve atm_iy_1xor2vp atm_l0_15vqwwr atm_l1_1wugsn5 atm_l2_1f51e7f atm_lb_4n2dxu atm_lh_swyrjs atm_5sxl3l_16m390d__1v156lz favrsqg atm_n3_idpfg4 l1hvhoo atm_fq_idpfg4 dir dir-ltr&quot;]/div[@class=&quot;dvp1orm atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_l8_10us9ju dir dir-ltr&quot;]/div[@class=&quot;d1hw4v9n atm_e2_1osqo2v atm_j6_1665v6k dir dir-ltr&quot;]/div[@class=&quot;_g2s11rv&quot;]/div[1]/div[1]/div[@class=&quot;_14676s3&quot;]/div[@class=&quot;_1foj6yps&quot;]/div[@class=&quot;_2hyui6e&quot;]/div[@class=&quot;_1lds9wb&quot;]/div[@class=&quot;_ytfarf&quot;]/table[@class=&quot;_cvkwaj&quot;]/tbody[1]/tr[5]/td[@class=&quot;_sl5yz7r&quot;]/div[@class=&quot;_1xnkk5ra notranslate&quot;]</value>
      <webElementGuid>9eb03024-c53f-4e6d-9a40-21d66c29ec9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div[3]/div/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[5]/td/div</value>
      <webElementGuid>3a766d5a-575b-40eb-8a0c-ae8bc7aa5890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July 2024'])[1]/following::div[28]</value>
      <webElementGuid>a243ed91-35ea-493a-aaab-a406735412b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 2024'])[1]/following::div[61]</value>
      <webElementGuid>3dcc77ee-2146-4351-a256-5ce87d7d8829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='August 2024'])[1]/preceding::div[4]</value>
      <webElementGuid>503ae081-456c-40f8-ac32-0271fceb6315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='September 2024'])[1]/preceding::div[38]</value>
      <webElementGuid>d8794007-0f83-489a-a8b5-76e536fbea64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[5]/td/div</value>
      <webElementGuid>b3703471-30ed-464b-9f5e-9c580ab46c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '28' or . = '28')]</value>
      <webElementGuid>f29b342f-144d-4a6c-a039-d490d8c7880a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
