<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Experiences</name>
   <tag></tag>
   <elementGuidId>6b203c76-842c-4e0f-b14e-d1cd4e4abefb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.t1763h34.atm_gi_1sxbfl9.atm_mk_h2mmj6.atm_c8_1cw7z3g.atm_g3_92qb7l.atm_fr_1bq7tds.atm_cs_6adqpa.atm_gi_acfr1u__qky54b.atm_92_1yyfdc7_1v4k0id.atm_5j_qslrf5_1v4k0id.atm_6i_14idwd0_1v4k0id.atm_tk_14idwd0_1v4k0id.atm_fq_4h84z3_1v4k0id.atm_n3_4h84z3_1v4k0id.atm_mk_stnw88_1v4k0id.atm_wq_1mrwo0b_1v4k0id.atm_7l_dezgoh_1nos8r_uv4tnr.atm_26_116dmco_2tuxlq_uv4tnr.dir.dir-ltr > span.t13onqtt.atm_c8_16fp2vl.atm_g3_x9fz81.atm_fr_12ckmjc.atm_7l_c8dnct.atm_9s_116y0ak.atm_ar_1bp4okc.atm_7l_yn12i_1nos8r_uv4tnr.atm_92_1y40vl2_9in345.atm_e2_idpfg4_9in345.atm_vl_15vqwwr_9in345.atm_ks_15vqwwr_9in345.atm_vb_glywfm_9in345.atm_mj_glywfm_9in345.atm_cs_10d11i2_9in345.atm_9s_glywfm_9in345_1pvdnhc.dir.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search-block-tab-EXPERIENCES']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;header-tab-search-block-tab-EXPERIENCES&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d8641281-a994-4b8a-a7bc-b326d83eec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t13onqtt atm_c8_16fp2vl atm_g3_x9fz81 atm_fr_12ckmjc atm_7l_c8dnct atm_9s_116y0ak atm_ar_1bp4okc atm_7l_yn12i_1nos8r_uv4tnr atm_92_1y40vl2_9in345 atm_e2_idpfg4_9in345 atm_vl_15vqwwr_9in345 atm_ks_15vqwwr_9in345 atm_vb_glywfm_9in345 atm_mj_glywfm_9in345 atm_cs_10d11i2_9in345 atm_9s_glywfm_9in345_1pvdnhc dir dir-ltr</value>
      <webElementGuid>0d02c269-cde6-4178-bfa6-14b76b044c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-content</name>
      <type>Main</type>
      <value>Experiences</value>
      <webElementGuid>9a844a1c-9435-4e0e-a9b1-d3d4f37567ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Experiences</value>
      <webElementGuid>36bd6498-4e26-45e9-ad89-d978f5253f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-block-tab-EXPERIENCES&quot;)/div[@class=&quot;t1763h34 atm_gi_1sxbfl9 atm_mk_h2mmj6 atm_c8_1cw7z3g atm_g3_92qb7l atm_fr_1bq7tds atm_cs_6adqpa atm_gi_acfr1u__qky54b atm_92_1yyfdc7_1v4k0id atm_5j_qslrf5_1v4k0id atm_6i_14idwd0_1v4k0id atm_tk_14idwd0_1v4k0id atm_fq_4h84z3_1v4k0id atm_n3_4h84z3_1v4k0id atm_mk_stnw88_1v4k0id atm_wq_1mrwo0b_1v4k0id atm_7l_dezgoh_1nos8r_uv4tnr atm_26_116dmco_2tuxlq_uv4tnr dir dir-ltr&quot;]/span[@class=&quot;t13onqtt atm_c8_16fp2vl atm_g3_x9fz81 atm_fr_12ckmjc atm_7l_c8dnct atm_9s_116y0ak atm_ar_1bp4okc atm_7l_yn12i_1nos8r_uv4tnr atm_92_1y40vl2_9in345 atm_e2_idpfg4_9in345 atm_vl_15vqwwr_9in345 atm_ks_15vqwwr_9in345 atm_vb_glywfm_9in345 atm_mj_glywfm_9in345 atm_cs_10d11i2_9in345 atm_9s_glywfm_9in345_1pvdnhc dir dir-ltr&quot;]</value>
      <webElementGuid>7c695574-449e-4016-95e5-99f92b46da35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='search-block-tab-EXPERIENCES']/div/span</value>
      <webElementGuid>f6cb1b6a-881b-469d-a10a-ac825a34be06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stays'])[1]/following::span[1]</value>
      <webElementGuid>7ebab851-f2e0-4850-a3d8-704b55d865f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add guests'])[1]/following::span[2]</value>
      <webElementGuid>9ce766c8-cb03-4439-bd31-8cea06e2662e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where'])[1]/preceding::span[1]</value>
      <webElementGuid>dffe25bd-8e3a-4bbd-82f6-4b1e819d9618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by region'])[1]/preceding::span[1]</value>
      <webElementGuid>dcb9cc23-cf1c-40fd-90dd-f0f99a18fa58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Experiences']/parent::*</value>
      <webElementGuid>253d5533-96a9-4120-975f-69ea8fd73d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/span</value>
      <webElementGuid>05a67c82-a5f6-421b-aba0-7da3bbada8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Experiences' or . = 'Experiences')]</value>
      <webElementGuid>5e10808d-efbd-4783-9adc-164f70a48b0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
