<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Indonesia_a-button-input</name>
   <tag></tag>
   <elementGuidId>25743af2-b913-4146-86af-b37da47da87d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>389a0a27-5807-411a-b8ec-c69a6475d503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-params</name>
      <type>Main</type>
      <value>{&quot;toasterType&quot;:&quot;AIS_INGRESS&quot;}</value>
      <webElementGuid>2ec50cf1-5361-4032-8b88-4154b99b32f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-type</name>
      <type>Main</type>
      <value>DISMISS</value>
      <webElementGuid>f84430e1-c1d9-4adc-ac11-d5d976624eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>137573b8-6c87-4b86-a999-0f8b2c55e921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ba884534-fdbb-45bf-99e6-20a92dd7aadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-main&quot;)/div[@class=&quot;nav-left&quot;]/div[@class=&quot;a-section glow-toaster glow-toaster-theme-default glow-toaster-slot-default nav-coreFlyout nav-flyout&quot;]/div[@class=&quot;glow-toaster-content&quot;]/div[@class=&quot;glow-toaster-footer&quot;]/span[@class=&quot;a-button a-spacing-top-base a-button-base glow-toaster-button glow-toaster-button-dismiss a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>b945e44e-6b2d-4e95-b58e-c3f37163de1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[2]</value>
      <webElementGuid>d8b56695-a4f0-4629-bf1e-58579d38e01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-main']/div/div/div/div[3]/span/span/input</value>
      <webElementGuid>e6d63701-fe52-40fb-9aab-36790760ee42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>089a3c86-59a6-4985-9936-39a0fa403bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>1c93d355-31b5-4115-8399-efc66fd2c8a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
