<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_We found 23 results</name>
   <tag></tag>
   <elementGuidId>d2a68c10-aa91-4dbe-8c8b-0f817130ddd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.utility-bar__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-template--15857958813779__main']/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;We found 23 results&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19ff9aa6-e77e-4a61-9e37-9952465c25aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>utility-bar__item</value>
      <webElementGuid>674799e3-10c4-4eac-b57b-9a2b826a6c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We found 23 results</value>
      <webElementGuid>858e8b6b-0c98-46d6-8b04-967bfc088e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--15857958813779__main&quot;)/div[1]/div[@class=&quot;container container--no-max&quot;]/div[@class=&quot;utility-bar&quot;]/div[@class=&quot;utility-bar__centre&quot;]/div[@class=&quot;utility-bar__item&quot;]</value>
      <webElementGuid>2816b264-d0f7-46f6-9c9c-6920a19e44ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-template--15857958813779__main']/div/div[2]/div/div[2]/div</value>
      <webElementGuid>b80495f9-0562-42bd-ab9e-c0a247899218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::div[2]</value>
      <webElementGuid>e33b82bb-1f81-459b-9001-986a224b1059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/following::div[8]</value>
      <webElementGuid>532b625e-0eb5-4dbe-9a64-f8d0292a2c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/preceding::div[1]</value>
      <webElementGuid>880dbdb9-ee71-462e-9d0c-15c51f88cdff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[1]/preceding::div[2]</value>
      <webElementGuid>efd01263-85ba-4ef6-815c-8c3a9c78ed13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We found 23 results']/parent::*</value>
      <webElementGuid>28fb70a5-0551-4759-9f18-89c1851e1fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>5e17a29d-0d7c-496f-809b-91be6b4e1dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'We found 23 results' or . = 'We found 23 results')]</value>
      <webElementGuid>bf9d2856-1ffb-41a8-8374-83efe245eaf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
